package com.jsf.persistence;
// Generated 7/08/2016 09:46:15 PM by Hibernate Tools 3.6.0



/**
 * Bancos generated by hbm2java
 */
public class Bancos  implements java.io.Serializable {


     private int idbanco;
     private String sbanco;
     private String sbancobus;
     

    public Bancos() {
    }

    public Bancos(int idbanco, String sbanco) {
       this.idbanco = idbanco;
       this.sbanco = sbanco;
    }
   
    public int getIdbanco() {
        return this.idbanco;
    }
    
    public void setIdbanco(int idbanco) {
        this.idbanco = idbanco;
    }
    public String getSbanco() {
        return this.sbanco;
    }
    
    public void setSbanco(String sbanco) {
        this.sbanco = sbanco;
    }

    /**
     * @return the sbancobus
     */
    public String getSbancobus() {
        return sbancobus;
    }

    /**
     * @param sbancobus the sbancobus to set
     */
    public void setSbancobus(String sbancobus) {
        this.sbancobus = sbancobus;
    }




}


