package com.jsf.persistence;
// Generated 7/08/2016 09:46:15 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int idusuario;
     private String susuario;
     private String spassword;
     private Date defchaexpira;

    public Login() {
    }

    public Login(int idusuario, String susuario, String spassword, Date defchaexpira) {
       this.idusuario = idusuario;
       this.susuario = susuario;
       this.spassword = spassword;
       this.defchaexpira = defchaexpira;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getSusuario() {
        return this.susuario;
    }
    
    public void setSusuario(String susuario) {
        this.susuario = susuario;
    }
    public String getSpassword() {
        return this.spassword;
    }
    
    public void setSpassword(String spassword) {
        this.spassword = spassword;
    }
    public Date getDefchaexpira() {
        return this.defchaexpira;
    }
    
    public void setDefchaexpira(Date defchaexpira) {
        this.defchaexpira = defchaexpira;
    }




}


